<?php

namespace Database\Seeders;

use App\Models\AppSetting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // Pricing Settings
            [
                'key' => 'base_fare',
                'value' => '3.50',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Tarif de base',
                'description' => 'Prix minimum pour un trajet',
                'sort_order' => 1,
            ],
            [
                'key' => 'cost_per_km',
                'value' => '1.20',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Prix par km',
                'description' => 'Coût par kilomètre parcouru',
                'sort_order' => 2,
            ],
            [
                'key' => 'cost_per_minute',
                'value' => '0.30',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Prix par minute',
                'description' => 'Coût par minute d\'attente ou de trafic',
                'sort_order' => 3,
            ],
            [
                'key' => 'minimum_fare',
                'value' => '5.00',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Tarif minimum',
                'description' => 'Montant minimum pour un trajet',
                'sort_order' => 4,
            ],
            [
                'key' => 'minimum_distance',
                'value' => '2.0',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Distance minimum',
                'description' => 'Distance minimum facturée en km',
                'sort_order' => 5,
            ],
            [
                'key' => 'minimum_time',
                'value' => '5',
                'type' => 'integer',
                'category' => 'pricing',
                'display_name' => 'Temps minimum',
                'description' => 'Temps minimum facturé en minutes',
                'sort_order' => 6,
            ],
            [
                'key' => 'night_surcharge_percentage',
                'value' => '20',
                'type' => 'integer',
                'category' => 'pricing',
                'display_name' => 'Majoration nuit (%)',
                'description' => 'Pourcentage supplémentaire pour les trajets de nuit',
                'sort_order' => 7,
            ],
            [
                'key' => 'peak_hours_surcharge_percentage',
                'value' => '15',
                'type' => 'integer',
                'category' => 'pricing',
                'display_name' => 'Majoration heures de pointe (%)',
                'description' => 'Pourcentage supplémentaire pendant les heures de pointe',
                'sort_order' => 8,
            ],
            [
                'key' => 'airport_surcharge',
                'value' => '2.00',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Supplément aéroport',
                'description' => 'Supplément pour les trajets vers/depuis l\'aéroport',
                'sort_order' => 9,
            ],
            [
                'key' => 'booking_fee',
                'value' => '1.50',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Frais de réservation',
                'description' => 'Frais fixes pour chaque réservation',
                'sort_order' => 10,
            ],
            [
                'key' => 'service_tax_percentage',
                'value' => '5.0',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Taxe de service (%)',
                'description' => 'Taxe de service appliquée sur chaque course',
                'sort_order' => 11,
            ],
            [
                'key' => 'luggage_fee',
                'value' => '1.00',
                'type' => 'decimal',
                'category' => 'pricing',
                'display_name' => 'Frais de bagages',
                'description' => 'Frais supplémentaires par bagage',
                'sort_order' => 12,
            ],

            // Commission Settings
            [
                'key' => 'driver_commission_percentage',
                'value' => '80',
                'type' => 'integer',
                'category' => 'commission',
                'display_name' => 'Commission chauffeur (%)',
                'description' => 'Pourcentage que le chauffeur reçoit',
                'sort_order' => 1,
            ],
            [
                'key' => 'platform_commission_percentage',
                'value' => '20',
                'type' => 'integer',
                'category' => 'commission',
                'display_name' => 'Commission plateforme (%)',
                'description' => 'Pourcentage que la plateforme garde',
                'sort_order' => 2,
            ],
            [
                'key' => 'cancellation_fee_driver',
                'value' => '5.00',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Frais annulation (chauffeur)',
                'description' => 'Frais quand le chauffeur annule',
                'sort_order' => 3,
            ],
            [
                'key' => 'cancellation_fee_rider',
                'value' => '3.00',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Frais annulation (client)',
                'description' => 'Frais quand le client annule',
                'sort_order' => 4,
            ],
            [
                'key' => 'transaction_fee_percentage',
                'value' => '2.9',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Frais de transaction (%)',
                'description' => 'Frais de transaction bancaire/PayPal',
                'sort_order' => 5,
            ],
            [
                'key' => 'transaction_fee_fixed',
                'value' => '0.30',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Frais fixes transaction',
                'description' => 'Frais fixes par transaction',
                'sort_order' => 6,
            ],
            [
                'key' => 'minimum_commission',
                'value' => '2.00',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Commission minimum',
                'description' => 'Commission minimum garantie au chauffeur',
                'sort_order' => 7,
            ],
            [
                'key' => 'driver_referral_bonus',
                'value' => '50.00',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Bonus référence chauffeur',
                'description' => 'Bonus pour chaque chauffeur référencé',
                'sort_order' => 8,
            ],
            [
                'key' => 'rider_referral_bonus',
                'value' => '10.00',
                'type' => 'decimal',
                'category' => 'commission',
                'display_name' => 'Bonus référence client',
                'description' => 'Bonus pour chaque client référencé',
                'sort_order' => 9,
            ],

            // Vehicle Settings
            [
                'key' => 'vehicle_types',
                'value' => '["standard","comfort","premium","van","electric","motorcycle"]',
                'type' => 'array',
                'category' => 'vehicles',
                'display_name' => 'Types de véhicules',
                'description' => 'Types de véhicules disponibles',
                'sort_order' => 1,
            ],
            [
                'key' => 'standard_multiplier',
                'value' => '1.0',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Standard',
                'description' => 'Multiplicateur de prix pour les véhicules standard',
                'sort_order' => 2,
            ],
            [
                'key' => 'comfort_multiplier',
                'value' => '1.3',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Confort',
                'description' => 'Multiplicateur de prix pour les véhicules confort',
                'sort_order' => 3,
            ],
            [
                'key' => 'premium_multiplier',
                'value' => '1.8',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Premium',
                'description' => 'Multiplicateur de prix pour les véhicules premium',
                'sort_order' => 4,
            ],
            [
                'key' => 'van_multiplier',
                'value' => '2.0',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Van',
                'description' => 'Multiplicateur de prix pour les vans',
                'sort_order' => 5,
            ],
            [
                'key' => 'electric_multiplier',
                'value' => '1.1',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Électrique',
                'description' => 'Multiplicateur de prix pour les véhicules électriques',
                'sort_order' => 6,
            ],
            [
                'key' => 'motorcycle_multiplier',
                'value' => '0.8',
                'type' => 'decimal',
                'category' => 'vehicles',
                'display_name' => 'Multiplicateur Moto',
                'description' => 'Multiplicateur de prix pour les motos',
                'sort_order' => 7,
            ],
            [
                'key' => 'max_vehicle_age_years',
                'value' => '10',
                'type' => 'integer',
                'category' => 'vehicles',
                'display_name' => 'Âge maximum véhicule (années)',
                'description' => 'Âge maximum autorisé pour les véhicules',
                'sort_order' => 8,
            ],
            [
                'key' => 'max_passengers_standard',
                'value' => '4',
                'type' => 'integer',
                'category' => 'vehicles',
                'display_name' => 'Passagers maximum (Standard)',
                'description' => 'Nombre maximum de passagers pour standard',
                'sort_order' => 9,
            ],
            [
                'key' => 'max_passengers_van',
                'value' => '8',
                'type' => 'integer',
                'category' => 'vehicles',
                'display_name' => 'Passagers maximum (Van)',
                'description' => 'Nombre maximum de passagers pour van',
                'sort_order' => 10,
            ],

            // Driver Settings
            [
                'key' => 'driver_approval_required',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'drivers',
                'display_name' => 'Approval chauffeur requis',
                'description' => 'Les chauffeurs doivent être approuvés manuellement',
                'sort_order' => 1,
            ],
            [
                'key' => 'minimum_driver_rating',
                'value' => '4.0',
                'type' => 'decimal',
                'category' => 'drivers',
                'display_name' => 'Note minimum chauffeur',
                'description' => 'Note minimum pour rester actif sur la plateforme',
                'sort_order' => 2,
            ],
            [
                'key' => 'driver_online_hours_limit',
                'value' => '12',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Limite heures en ligne',
                'description' => 'Nombre maximum d\'heures continues en ligne',
                'sort_order' => 3,
            ],
            [
                'key' => 'driver_commission_payout_days',
                'value' => '7',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Jours avant paiement',
                'description' => 'Nombre de jours avant le paiement des commissions',
                'sort_order' => 4,
            ],
            [
                'key' => 'minimum_driver_age',
                'value' => '21',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Âge minimum chauffeur',
                'description' => 'Âge minimum requis pour être chauffeur',
                'sort_order' => 5,
            ],
            [
                'key' => 'minimum_driving_experience',
                'value' => '2',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Expérience minimum conduite',
                'description' => 'Années d\'expérience minimum requise',
                'sort_order' => 6,
            ],
            [
                'key' => 'max_accept_distance_km',
                'value' => '5.0',
                'type' => 'decimal',
                'category' => 'drivers',
                'display_name' => 'Distance max acceptation (km)',
                'description' => 'Distance maximum pour accepter une course',
                'sort_order' => 7,
            ],
            [
                'key' => 'max_response_time_seconds',
                'value' => '30',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Temps réponse max (sec)',
                'description' => 'Temps maximum pour accepter une course',
                'sort_order' => 8,
            ],
            [
                'key' => 'minimum_acceptance_rate',
                'value' => '85',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Taux acceptation minimum (%)',
                'description' => 'Taux d\'acceptation minimum requis',
                'sort_order' => 9,
            ],
            [
                'key' => 'maximum_cancellation_rate',
                'value' => '10',
                'type' => 'integer',
                'category' => 'drivers',
                'display_name' => 'Taux annulation maximum (%)',
                'description' => 'Taux d\'annulation maximum autorisé',
                'sort_order' => 10,
            ],

            // Trip Settings
            [
                'key' => 'max_waiting_time_minutes',
                'value' => '5',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Temps d\'attente maximum (minutes)',
                'description' => 'Temps d\'attente maximum gratuit',
                'sort_order' => 1,
            ],
            [
                'key' => 'search_radius_km',
                'value' => '5',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Rayon de recherche (km)',
                'description' => 'Rayon pour trouver les chauffeurs disponibles',
                'sort_order' => 2,
            ],
            [
                'key' => 'trip_cancellation_window_minutes',
                'value' => '2',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Fenêtre annulation gratuite (minutes)',
                'description' => 'Temps pour annuler gratuitement après acceptation',
                'sort_order' => 3,
            ],
            [
                'key' => 'advance_booking_hours',
                'value' => '24',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Réservation à l\'avance (heures)',
                'description' => 'Nombre d\'heures maximum pour réserver à l\'avance',
                'sort_order' => 4,
            ],
            [
                'key' => 'max_trip_distance_km',
                'value' => '100',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Distance maximum course (km)',
                'description' => 'Distance maximum autorisée pour une course',
                'sort_order' => 5,
            ],
            [
                'key' => 'max_trip_duration_minutes',
                'value' => '180',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Durée maximum course (minutes)',
                'description' => 'Durée maximum autorisée pour une course',
                'sort_order' => 6,
            ],
            [
                'key' => 'max_stops_per_trip',
                'value' => '3',
                'type' => 'integer',
                'category' => 'trips',
                'display_name' => 'Nombre maximum arrêts',
                'description' => 'Nombre maximum d\'arrêts autorisés par course',
                'sort_order' => 7,
            ],
            [
                'key' => 'additional_stop_fee',
                'value' => '2.00',
                'type' => 'decimal',
                'category' => 'trips',
                'display_name' => 'Frais arrêt supplémentaire',
                'description' => 'Frais pour chaque arrêt supplémentaire',
                'sort_order' => 8,
            ],
            [
                'key' => 'show_trip_estimate',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'trips',
                'display_name' => 'Estimation temps trajet',
                'description' => 'Afficher l\'estimation du temps de trajet',
                'sort_order' => 9,
            ],
            [
                'key' => 'enable_ride_sharing',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'trips',
                'display_name' => 'Partage trajet',
                'description' => 'Autoriser le partage de trajet',
                'sort_order' => 10,
            ],

            // Payment Settings
            [
                'key' => 'payment_methods',
                'value' => '["cash","card","mobile_money","paypal","bank_transfer"]',
                'type' => 'array',
                'category' => 'payments',
                'display_name' => 'Méthodes de paiement',
                'description' => 'Méthodes de paiement acceptées',
                'sort_order' => 1,
            ],
            [
                'key' => 'minimum_wallet_balance',
                'value' => '10.00',
                'type' => 'decimal',
                'category' => 'payments',
                'display_name' => 'Solde minimum portefeuille',
                'description' => 'Solde minimum requis dans le portefeuille',
                'sort_order' => 2,
            ],
            [
                'key' => 'driver_payout_threshold',
                'value' => '50.00',
                'type' => 'decimal',
                'category' => 'payments',
                'display_name' => 'Seuil paiement chauffeur',
                'description' => 'Montant minimum pour demander un paiement',
                'sort_order' => 3,
            ],
            [
                'key' => 'currency',
                'value' => 'EUR',
                'type' => 'string',
                'category' => 'payments',
                'display_name' => 'Devise',
                'description' => 'Devise principale de l\'application',
                'sort_order' => 4,
            ],
            [
                'key' => 'exchange_rate_usd',
                'value' => '0.85',
                'type' => 'decimal',
                'category' => 'payments',
                'display_name' => 'Taux de change USD',
                'description' => 'Taux de change USD vers devise locale',
                'sort_order' => 5,
            ],
            [
                'key' => 'withdrawal_fee',
                'value' => '1.00',
                'type' => 'decimal',
                'category' => 'payments',
                'display_name' => 'Frais retrait',
                'description' => 'Frais pour chaque retrait d\'argent',
                'sort_order' => 6,
            ],
            [
                'key' => 'withdrawal_minimum_percentage',
                'value' => '50',
                'type' => 'integer',
                'category' => 'payments',
                'display_name' => 'Retrait minimum (%)',
                'description' => 'Pourcentage minimum pour retrait',
                'sort_order' => 7,
            ],
            [
                'key' => 'auto_payment_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'payments',
                'display_name' => 'Paiement automatique',
                'description' => 'Activer les paiements automatiques',
                'sort_order' => 8,
            ],
            [
                'key' => 'force_prepayment',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'payments',
                'display_name' => 'Forcer pré-paiement',
                'description' => 'Forcer le pré-paiement pour toutes les courses',
                'sort_order' => 9,
            ],

            // Notification Settings
            [
                'key' => 'send_sms_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notifications SMS',
                'description' => 'Activer les notifications SMS',
                'sort_order' => 1,
            ],
            [
                'key' => 'send_email_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notifications Email',
                'description' => 'Activer les notifications email',
                'sort_order' => 2,
            ],
            [
                'key' => 'send_push_notifications',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notifications Push',
                'description' => 'Activer les notifications push',
                'sort_order' => 3,
            ],
            [
                'key' => 'driver_notifications_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notifications chauffeur',
                'description' => 'Activer les notifications pour les chauffeurs',
                'sort_order' => 4,
            ],
            [
                'key' => 'rider_notifications_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notifications client',
                'description' => 'Activer les notifications pour les clients',
                'sort_order' => 5,
            ],
            [
                'key' => 'new_trip_notification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notification nouvelle course',
                'description' => 'Notifier pour les nouvelles courses',
                'sort_order' => 6,
            ],
            [
                'key' => 'cancellation_notification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notification annulation',
                'description' => 'Notifier pour les annulations',
                'sort_order' => 7,
            ],
            [
                'key' => 'payment_notification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notification paiement',
                'description' => 'Notifier pour les paiements',
                'sort_order' => 8,
            ],
            [
                'key' => 'promotion_notification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'notifications',
                'display_name' => 'Notification promotion',
                'description' => 'Notifier pour les promotions',
                'sort_order' => 9,
            ],
            [
                'key' => 'notification_frequency_hours',
                'value' => '1',
                'type' => 'integer',
                'category' => 'notifications',
                'display_name' => 'Fréquence notifications (heures)',
                'description' => 'Fréquence minimum entre notifications',
                'sort_order' => 10,
            ],

            // Application Settings
            [
                'key' => 'app_name',
                'value' => 'TaxiApp Pro',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Nom de l\'application',
                'description' => 'Nom affiché dans l\'application',
                'sort_order' => 1,
            ],
            [
                'key' => 'app_version',
                'value' => '1.0.0',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Version de l\'application',
                'description' => 'Version actuelle de l\'application',
                'sort_order' => 2,
            ],
            [
                'key' => 'support_email',
                'value' => 'support@taxiapp.com',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Email support',
                'description' => 'Email du support client',
                'sort_order' => 3,
            ],
            [
                'key' => 'support_phone',
                'value' => '+33123456789',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Téléphone support',
                'description' => 'Numéro de téléphone du support',
                'sort_order' => 4,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'application',
                'display_name' => 'Mode maintenance',
                'description' => 'Mettre l\'application en mode maintenance',
                'sort_order' => 5,
            ],
            [
                'key' => 'debug_mode',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'application',
                'display_name' => 'Mode debug',
                'description' => 'Activer le mode debug',
                'sort_order' => 6,
            ],
            [
                'key' => 'api_rate_limit',
                'value' => '60',
                'type' => 'integer',
                'category' => 'application',
                'display_name' => 'Limite requêtes API',
                'description' => 'Nombre maximum de requêtes par minute',
                'sort_order' => 7,
            ],
            [
                'key' => 'cache_duration_minutes',
                'value' => '10',
                'type' => 'integer',
                'category' => 'application',
                'display_name' => 'Cache durée (minutes)',
                'description' => 'Durée de cache des données',
                'sort_order' => 8,
            ],
            [
                'key' => 'session_lifetime_minutes',
                'value' => '120',
                'type' => 'integer',
                'category' => 'application',
                'display_name' => 'Session durée (minutes)',
                'description' => 'Durée de vie des sessions',
                'sort_order' => 9,
            ],
            [
                'key' => 'timezone',
                'value' => 'Europe/Paris',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Fuseau horaire',
                'description' => 'Fuseau horaire de l\'application',
                'sort_order' => 10,
            ],
            [
                'key' => 'default_language',
                'value' => 'fr',
                'type' => 'string',
                'category' => 'application',
                'display_name' => 'Langue par défaut',
                'description' => 'Langue par défaut de l\'application',
                'sort_order' => 11,
            ],

            // Safety Settings
            [
                'key' => 'sos_button_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Bouton SOS',
                'description' => 'Activer le bouton SOS dans l\'application',
                'sort_order' => 1,
            ],
            [
                'key' => 'live_trip_sharing',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Partage trajet en direct',
                'description' => 'Permettre le partage de position en direct',
                'sort_order' => 2,
            ],
            [
                'key' => 'selfie_verification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Vérification selfie',
                'description' => 'Vérification selfie pour les chauffeurs',
                'sort_order' => 3,
            ],
            [
                'key' => 'audio_recording',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Enregistrement audio',
                'description' => 'Enregistrement audio pendant les trajets',
                'sort_order' => 4,
            ],
            [
                'key' => 'mask_phone_numbers',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Masquer numéro',
                'description' => 'Masquer les numéros de téléphone',
                'sort_order' => 5,
            ],
            [
                'key' => 'otp_verification',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Vérification OTP',
                'description' => 'Vérification OTP pour les trajets',
                'sort_order' => 6,
            ],
            [
                'key' => 'age_verification',
                'value' => 'false',
                'type' => 'boolean',
                'category' => 'safety',
                'display_name' => 'Vérification âge client',
                'description' => 'Vérifier l\'âge des clients',
                'sort_order' => 7,
            ],
            [
                'key' => 'minimum_rider_age',
                'value' => '18',
                'type' => 'integer',
                'category' => 'safety',
                'display_name' => 'Âge minimum client',
                'description' => 'Âge minimum requis pour utiliser l\'application',
                'sort_order' => 8,
            ],
            [
                'key' => 'sos_response_time_seconds',
                'value' => '60',
                'type' => 'integer',
                'category' => 'safety',
                'display_name' => 'Temps SOS réponse (sec)',
                'description' => 'Temps maximum pour répondre au SOS',
                'sort_order' => 9,
            ],

            // Geofencing Settings
            [
                'key' => 'geofencing_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'geofencing',
                'display_name' => 'Activer géofencing',
                'description' => 'Activer le géofencing',
                'sort_order' => 1,
            ],
            [
                'key' => 'service_area_radius_km',
                'value' => '50',
                'type' => 'integer',
                'category' => 'geofencing',
                'display_name' => 'Zone de service (km)',
                'description' => 'Rayon de la zone de service',
                'sort_order' => 2,
            ],
            [
                'key' => 'out_of_service_area_penalty',
                'value' => '10.00',
                'type' => 'decimal',
                'category' => 'geofencing',
                'display_name' => 'Pénalité hors zone',
                'description' => 'Pénalité pour trajet hors zone',
                'sort_order' => 3,
            ],
            [
                'key' => 'gps_accuracy_meters',
                'value' => '50',
                'type' => 'integer',
                'category' => 'geofencing',
                'display_name' => 'Précision GPS (mètres)',
                'description' => 'Précision requise pour la géolocalisation',
                'sort_order' => 4,
            ],
            [
                'key' => 'location_update_interval_seconds',
                'value' => '10',
                'type' => 'integer',
                'category' => 'geofencing',
                'display_name' => 'Intervalle position (sec)',
                'description' => 'Intervalle de mise à jour de la position',
                'sort_order' => 5,
            ],
            [
                'key' => 'restricted_zones_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'geofencing',
                'display_name' => 'Zones interdites',
                'description' => 'Activer les zones interdites',
                'sort_order' => 6,
            ],
            [
                'key' => 'airport_zone_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'geofencing',
                'display_name' => 'Zone aéroport',
                'description' => 'Zone spéciale pour l\'aéroport',
                'sort_order' => 7,
            ],
            [
                'key' => 'downtown_zone_enabled',
                'value' => 'true',
                'type' => 'boolean',
                'category' => 'geofencing',
                'display_name' => 'Zone centre-ville',
                'description' => 'Zone spéciale pour le centre-ville',
                'sort_order' => 8,
            ],
            [
                'key' => 'airport_zone_radius_km',
                'value' => '2.0',
                'type' => 'decimal',
                'category' => 'geofencing',
                'display_name' => 'Rayon zone aéroport (km)',
                'description' => 'Rayon de la zone aéroport',
                'sort_order' => 9,
            ],
            [
                'key' => 'downtown_zone_radius_km',
                'value' => '1.5',
                'type' => 'decimal',
                'category' => 'geofencing',
                'display_name' => 'Rayon zone centre-ville (km)',
                'description' => 'Rayon de la zone centre-ville',
                'sort_order' => 10,
            ],
        ];

        foreach ($settings as $setting) {
            AppSetting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}